/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicCountdown: typeof import('./components/BasicCountdown.vue')['default']
    BasicFixedBottom: typeof import('./components/BasicFixedBottom.vue')['default']
    BasicLoading: typeof import('./components/BasicLoading.vue')['default']
    BasicModal: typeof import('./components/BasicModal.vue')['default']
    BasicPopup: typeof import('./components/BasicPopup.vue')['default']
    BasicTabbar: typeof import('./components/BasicTabbar.vue')['default']
    BasicToast: typeof import('./components/BasicToast.vue')['default']
    BasicWxOpenSubscribe: typeof import('./components/BasicWxOpenSubscribe.vue')['default']
    BizBanner: typeof import('./components/BizBanner.vue')['default']
    BizBlockEmpty: typeof import('./components/BizBlockEmpty.vue')['default']
    BizBlockError: typeof import('./components/BizBlockError.vue')['default']
    BizLatestChapter: typeof import('./components/BizLatestChapter.vue')['default']
    BizPopupBookTOC: typeof import('./components/BizPopupBookTOC.vue')['default']
    BizTrackClick: typeof import('./components/BizTrackClick.vue')['default']
    BizWidgetLatestChapter: typeof import('./components/BizWidgetLatestChapter.vue')['default']
    IAssetsIconCheck: typeof import('~icons/assets/icon-check')['default']
    IAssetsIconClose: typeof import('~icons/assets/icon-close')['default']
    IAssetsIconDoubleDown: typeof import('~icons/assets/icon-double-down')['default']
    IAssetsIconLock: typeof import('~icons/assets/icon-lock')['default']
    IAssetsIconSearch: typeof import('~icons/assets/icon-search')['default']
    IAssetsIconTabCategory: typeof import('~icons/assets/icon-tab-category')['default']
    IAssetsIconTabCategoryActive: typeof import('~icons/assets/icon-tab-category-active')['default']
    IAssetsIconTabHistory: typeof import('~icons/assets/icon-tab-history')['default']
    IAssetsIconTabHistoryActive: typeof import('~icons/assets/icon-tab-history-active')['default']
    IAssetsIconTabHome: typeof import('~icons/assets/icon-tab-home')['default']
    IAssetsIconTabHomeActive: typeof import('~icons/assets/icon-tab-home-active')['default']
    IAssetsIconTabMe: typeof import('~icons/assets/icon-tab-me')['default']
    IAssetsIconTabMeActive: typeof import('~icons/assets/icon-tab-me-active')['default']
    ICarbonCaretDown: typeof import('~icons/carbon/caret-down')['default']
    IFeSearch: typeof import('~icons/fe/search')['default']
    IIconParkOutlineCloseOne: typeof import('~icons/icon-park-outline/close-one')['default']
    IIconParkOutlineHome: typeof import('~icons/icon-park-outline/home')['default']
    IIconParkOutlineLeft: typeof import('~icons/icon-park-outline/left')['default']
    IIconParkOutlineLoading: typeof import('~icons/icon-park-outline/loading')['default']
    IIconParkOutlineQuote: typeof import('~icons/icon-park-outline/quote')['default']
    IIconParkOutlineRight: typeof import('~icons/icon-park-outline/right')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
